import type { Metadata } from "next";
import "./globals.css";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Hero from "@/components/Hero";
import Brand from "@/components/Brand";
import Community from "@/components/Community";
import LearnMore from "@/components/LearnMore";
import HelpSection from "@/components/HelpSection";
import SecondHero from "@/components/SecondHero";
import Product from "@/components/Product";
import GetDemo from "@/components/GetDemo";
import MarketSection from "@/components/MarketSection";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "flex flex-col min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <Header />
        <Hero />
        <Brand />
        <Community />
        <LearnMore />
        <HelpSection />
        <SecondHero />
        <Product />
        <MarketSection />
        <GetDemo />
        <main className="flex-1">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
